name: geproye
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0-367.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_webrtc: ^0.9.32
  google_fonts: ^4.0.4
  http: ^0.13.6
  intl: ^0.18.1
  peerdart: ^0.5.0
  provider: ^6.0.5
  socket_io_client: ^2.0.2
  supabase_flutter: ^1.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    #- .env
    - assets/images/
